# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username:
  password: 
  port: 5432 

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: 
  password:
  database: HamsterTracker_development
  port: 5432  

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  username:
  password: 
  database: HamsterTracker_test
  port: 5432 

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: HamsterTracker_production
  username: HamsterTracker
  password: <%= ENV['HAMSTERTRACKER_DATABASE_PASSWORD'] %>
  port: 5432 